name: pokedex
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DI
  get_it: ^7.6.6
  injectable: ^2.3.2

  # Navigation
  auto_route: ^7.8.4

  # Parsing
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  cached_network_image: ^3.2.3
  sliding_up_panel: ^2.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  intl: ^0.19.0
  stream_transform: ^2.1.0
  flutter_web_frame: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.4.0
  auto_route_generator: ^7.3.2
  freezed: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/files/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900

flutter_gen:
  output: lib/presenter/
  line_length: 100
